[package]
name = "lookup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merlin = "3.0.0"
ark-ff = "0.4.2"
ark-poly = "0.4.2"

[dev-dependencies]
ark-bls12-381 = "0.4.0"
kzg = {path = "../kzg"}

